---
resource_types:
- name: artifactory
  type: docker-image
  source:
    repository: pivotalservices/artifactory-resource

groups:
  - name: Build
    jobs: 
      - release-candidate-version
      - build

resources:
  - name: philipshome
    type: git
    source:
      uri: https://github.com/satishnaidu/philipshome.git
      branch: develop
      username: ((service_user))
      password: ((service_pw))
  - name: version
    type: semver
    source:
      driver: git
      uri: https://gist.github.com/f1b5fd104e50bdf44c2a76917bdc7721.git
      branch: master
      file: philipshome.version
      username: ((service_user))
      password: ((service_pw))

jobs:
  - name: release-candidate-version
    serial: true
    plan:
      - get: philipshome
        trigger: true
      - get: version
        params: {pre: rc}
      - put: version
        params: {file: version/number}
      - task: update-version
        file: philipshome/ci/tasks/version_source.yml
      - put: philipshome
        params: {repository: updated-philipshome}
  - name: build
    plan:
      - get: version
        trigger: true
        passed: [release-candidate-version]
      - get: philipshome
        trigger: true
        passed: [release-candidate-version]
      - task: run-build
        file: philipshome/ci/tasks/run_build.yml
        params:
          ARTIFACTORY_USER: ((artifactory_user))
          ARTIFACTORY_PW: ((artifactory_pwd))
          ARTIFACTORY_URL: ((artifactory_url))
#      - put: artifactory-repository
#        params: { file: ./artifactory-repository/noise-localizer*.war }
  